#!/bin/bash
# SSH to a host as root via admin-00 in one step.
if [ ! $1 ]
then
	echo "Usage: rnull <hostname>"
	exit 1
fi
targethost=$1
echo -ne "\033]0;root@$targethost\007"
ssh -A -X -t gmason@admin-00.i "ssh -t -o \"GlobalKnownHostsFile /dev/null\" -o \"UserKnownHostsFile /dev/null\" -o \"StrictHostKeyChecking no\" root@$targethost"
