#!/bin/bash
# SSH to a host as root via admin-00 in one step.
# stupid hack for admin-00
export TERM="xterm"
if [ ! $1 ]
then
	echo "Usage: root <hostname>"
	exit 1
fi
targethost=$1
echo -ne "\033]0;root@$targethost\007"
#ssh -A -X -t gmason@192.168.0.19 "export TERM="xterm" && ssh -t root@$targethost"
ssh -A -t gmason@192.168.0.19 "export TERM="xterm" && ssh -t root@$targethost"
