#!/bin/bash
# SSH to a host as root via admin-00 in one step.
export TERM='xterm'
if [ ! $1 ]
then
	echo "Usage: root <hostname>"
	exit 1
fi
targethost=$1
echo -ne "\033]0;root@$targethost\007"
ssh -C -A -X -t -p 31337 gmason@localhost "ssh -t root@$targethost"
